// packages/react/src/button.tsx
import type { ComponentPropsWithRef } from "react";
import { buttonRecipe, partAttrs, type VariantProps } from "@moderno/core";

export interface ButtonProps
  extends ComponentPropsWithRef<"button">, VariantProps<typeof buttonRecipe.variants> {}

/**
 * Button — the reference primitive that establishes the Moderno pattern.
 *
 * There is no Ark "button" machine (a button needs no headless behaviour), so
 * this is the purest illustration of the contract: a plain element carrying
 * `data-scope`/`data-part` plus the recipe's `data-variant`/`data-size`. Every
 * pixel of styling comes from `components.css` keyed on those attributes — the
 * component holds zero colour, radius, or font. Switching brand (re-mapping the
 * token slots) re-themes it without touching this file.
 *
 * Consumer-supplied props win for behaviour (onClick, aria-*, className), while
 * the scope/part/variant attributes are applied last so they can't be clobbered.
 */
export function Button({ variant, size, type, children, ...rest }: ButtonProps) {
  return (
    <button
      type={type ?? "button"}
      {...rest}
      {...partAttrs("button", "root")}
      {...buttonRecipe({ variant, size })}
    >
      {children}
    </button>
  );
}

// packages/svelte/src/Button.svelte
<!--
  Button — the reference primitive, ported to Svelte 5.

  Identical contract to @moderno/react: a plain <button> carrying
  data-scope/data-part plus the shared buttonRecipe's data-variant/data-size.
  Zero styling lives here — components.css paints it from token slots. Consumer
  attributes (onclick, aria-*, class) spread first; the scope/part/variant attrs
  spread last so they can't be clobbered, mirroring the React prop order.
-->
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLButtonAttributes } from "svelte/elements";
  import { buttonRecipe, partAttrs, type VariantProps } from "@moderno/core";

  type ButtonVariant = NonNullable<VariantProps<typeof buttonRecipe.variants>["variant"]>;
  type ButtonSize = NonNullable<VariantProps<typeof buttonRecipe.variants>["size"]>;

  interface Props extends HTMLButtonAttributes {
    variant?: ButtonVariant;
    size?: ButtonSize;
    children?: Snippet;
  }

  let { variant, size, type, children, ...rest }: Props = $props();
</script>

<button
  type={type ?? "button"}
  {...rest}
  {...partAttrs("button", "root")}
  {...buttonRecipe({ variant, size })}
>
  {@render children?.()}
</button>
