// packages/react/src/spinner.tsx
import type { ComponentPropsWithRef } from "react";
import { partAttrs, spinnerRecipe, type VariantProps } from "@moderno-ui/core";

export interface SpinnerProps
  extends
    Omit<ComponentPropsWithRef<"span">, "children">,
    VariantProps<typeof spinnerRecipe.variants> {
  /** What is loading, read by screen readers. */
  label?: string;
}

/**
 * Spinner — a spinning ring that says "something is loading" without a
 * progress value.
 *
 * CSS-only: the root is a `<span role="status">` carrying
 * `data-scope`/`data-part` plus `spinnerRecipe`'s `data-size`. Inside, the
 * `circle` part is the ring (hidden from assistive tech) and the `label` part
 * is visually hidden text, so screen readers read "Loading" (or `label`).
 * The ring paints with the text colour around it.
 */
export function Spinner({ size, label = "Loading", ...rest }: SpinnerProps) {
  return (
    <span role="status" {...rest} {...partAttrs("spinner", "root")} {...spinnerRecipe({ size })}>
      <span aria-hidden="true" {...partAttrs("spinner", "circle")} />
      <span {...partAttrs("spinner", "label")}>{label}</span>
    </span>
  );
}

export type { SpinnerSize } from "@moderno-ui/core";

// packages/svelte/src/Spinner.svelte
<!--
  Spinner — a spinning ring that says "something is loading" without a
  progress value, ported to Svelte 5.

  Identical contract to @moderno-ui/react: a <span role="status"> root carrying
  data-scope/data-part plus the shared spinnerRecipe's data-size. The circle
  part is the ring, hidden from assistive tech; the label part is visually
  hidden text read by screen readers ("Loading", or `label`). The scope/part/
  size attrs spread last so they can't be clobbered.
-->
<script lang="ts">
  import type { HTMLAttributes } from "svelte/elements";
  import { partAttrs, spinnerRecipe, type SpinnerSize } from "@moderno-ui/core";

  interface Props extends Omit<HTMLAttributes<HTMLSpanElement>, "children"> {
    size?: SpinnerSize;
    /** What is loading, read by screen readers. */
    label?: string;
  }

  let { size, label = "Loading", ...rest }: Props = $props();
</script>

<span role="status" {...rest} {...partAttrs("spinner", "root")} {...spinnerRecipe({ size })}>
  <span aria-hidden="true" {...partAttrs("spinner", "circle")}></span>
  <span {...partAttrs("spinner", "label")}>{label}</span>
</span>
