// packages/solid/src/callout.tsx
import { splitProps, type JSX } from "solid-js";
import { calloutRecipe, partAttrs, type CalloutVariant } from "@moderno-ui/core";

export interface CalloutRootProps extends JSX.HTMLAttributes<HTMLDivElement> {
  variant?: CalloutVariant;
}

/** Props of every non-root Callout part: a plain div, styled by its `data-part`. */
export type CalloutPartProps = JSX.HTMLAttributes<HTMLDivElement>;

/**
 * Callout — a soft note inside the page's content, ported to Solid.
 *
 * Identical contract to `@moderno-ui/react`: a CSS-only primitive whose parts
 * carry `data-scope`/`data-part` plus the shared `calloutRecipe`'s
 * `data-variant`, painted entirely by `components.css`. The root is
 * `role="note"`, resolved (not spread over), so a consumer's `role` wins while
 * `undefined` keeps the default.
 */
export function CalloutRoot(props: CalloutRootProps) {
  const [local, rest] = splitProps(props, ["variant", "role", "children"]);
  return (
    <div
      {...rest}
      role={local.role ?? "note"}
      {...partAttrs("callout", "root")}
      {...calloutRecipe({ variant: local.variant })}
    >
      {local.children}
    </div>
  );
}

export function CalloutIcon(props: CalloutPartProps) {
  const [local, rest] = splitProps(props, ["children", "aria-hidden"]);
  return (
    <div {...rest} aria-hidden={local["aria-hidden"] ?? true} {...partAttrs("callout", "icon")}>
      {local.children}
    </div>
  );
}

export function CalloutContent(props: CalloutPartProps) {
  const [local, rest] = splitProps(props, ["children"]);
  return (
    <div {...rest} {...partAttrs("callout", "content")}>
      {local.children}
    </div>
  );
}

export function CalloutTitle(props: CalloutPartProps) {
  const [local, rest] = splitProps(props, ["children"]);
  return (
    <div {...rest} {...partAttrs("callout", "title")}>
      {local.children}
    </div>
  );
}

export function CalloutDescription(props: CalloutPartProps) {
  const [local, rest] = splitProps(props, ["children"]);
  return (
    <div {...rest} {...partAttrs("callout", "description")}>
      {local.children}
    </div>
  );
}

/** The Callout anatomy, namespaced like every other Moderno primitive. */
export const Callout = {
  Root: CalloutRoot,
  Icon: CalloutIcon,
  Content: CalloutContent,
  Title: CalloutTitle,
  Description: CalloutDescription,
};

export type { CalloutVariant } from "@moderno-ui/core";

// packages/react/src/callout.tsx
import type { ComponentPropsWithRef } from "react";
import { calloutRecipe, partAttrs, type VariantProps } from "@moderno-ui/core";

export interface CalloutRootProps
  extends ComponentPropsWithRef<"div">, VariantProps<typeof calloutRecipe.variants> {}

/** Props of every non-root Callout part: a plain div, styled by its `data-part`. */
export type CalloutPartProps = ComponentPropsWithRef<"div">;

/**
 * Callout — a soft note inside the page's content: a tip, a caveat, a
 * heads-up the reader should not miss.
 *
 * A CSS-only primitive, like Alert: elements carrying `data-scope`/`data-part`
 * plus the recipe's `data-variant`, with every pixel coming from
 * `components.css`. It differs from Alert in what it means, not only in how it
 * looks: a callout is part of the content, so its root is `role="note"`
 * rather than a live region, and nothing is announced when it renders.
 *
 * `role` is resolved like Alert's — a consumer's `role` wins, but passing
 * `undefined` keeps the default instead of erasing the attribute. `Icon` is a
 * slot, never an icon set, and is decorative by default.
 */
export function CalloutRoot({ variant, role, children, ...rest }: CalloutRootProps) {
  return (
    <div
      {...rest}
      role={role ?? "note"}
      {...partAttrs("callout", "root")}
      {...calloutRecipe({ variant })}
    >
      {children}
    </div>
  );
}

export function CalloutIcon({ children, "aria-hidden": ariaHidden, ...rest }: CalloutPartProps) {
  return (
    <div {...rest} aria-hidden={ariaHidden ?? true} {...partAttrs("callout", "icon")}>
      {children}
    </div>
  );
}

export function CalloutContent({ children, ...rest }: CalloutPartProps) {
  return (
    <div {...rest} {...partAttrs("callout", "content")}>
      {children}
    </div>
  );
}

export function CalloutTitle({ children, ...rest }: CalloutPartProps) {
  return (
    <div {...rest} {...partAttrs("callout", "title")}>
      {children}
    </div>
  );
}

export function CalloutDescription({ children, ...rest }: CalloutPartProps) {
  return (
    <div {...rest} {...partAttrs("callout", "description")}>
      {children}
    </div>
  );
}

/** The Callout anatomy, namespaced like every other Moderno primitive. */
export const Callout = {
  Root: CalloutRoot,
  Icon: CalloutIcon,
  Content: CalloutContent,
  Title: CalloutTitle,
  Description: CalloutDescription,
};

export type { CalloutVariant } from "@moderno-ui/core";
