// packages/react/src/alert.tsx
import type { ComponentPropsWithRef } from "react";
import { alertRecipe, alertRole, partAttrs, type VariantProps } from "@moderno-ui/core";

export interface AlertRootProps
  extends ComponentPropsWithRef<"div">, VariantProps<typeof alertRecipe.variants> {}

/** Props of every non-root Alert part: a plain div, styled by its `data-part`. */
export type AlertPartProps = ComponentPropsWithRef<"div">;

/**
 * Alert — an inline, page-level status message.
 *
 * A CSS-only primitive: Ark has no alert machine because there is no behaviour
 * to own — an alert is a static region. So, like Button, this is the pure form
 * of the contract: elements carrying `data-scope`/`data-part` plus the recipe's
 * `data-variant`/`data-size`, with every pixel coming from `components.css`.
 *
 * The anatomy is Ark-shaped (`root > icon + content(> title + description +
 * action)`) so a consumer overrides any part through `[data-part]` rather than a
 * wrapper class. `Icon` is a slot, never an icon set: primitives stay
 * icon-agnostic, so the consumer passes their own glyph and the part hands it
 * the status hue through `currentColor`.
 *
 * `role` defaults from `alertRole` (shared with every other binding) so the
 * urgent statuses announce assertively. It is resolved like Button's `type`
 * rather than spread over — a consumer's `role` wins, but passing `undefined`
 * keeps the default instead of erasing the attribute.
 */
export function AlertRoot({ variant, size, role, children, ...rest }: AlertRootProps) {
  return (
    <div
      {...rest}
      role={role ?? alertRole(variant)}
      {...partAttrs("alert", "root")}
      {...alertRecipe({ variant, size })}
    >
      {children}
    </div>
  );
}

export function AlertIcon({ children, "aria-hidden": ariaHidden, ...rest }: AlertPartProps) {
  return (
    <div {...rest} aria-hidden={ariaHidden ?? true} {...partAttrs("alert", "icon")}>
      {children}
    </div>
  );
}

export function AlertContent({ children, ...rest }: AlertPartProps) {
  return (
    <div {...rest} {...partAttrs("alert", "content")}>
      {children}
    </div>
  );
}

export function AlertTitle({ children, ...rest }: AlertPartProps) {
  return (
    <div {...rest} {...partAttrs("alert", "title")}>
      {children}
    </div>
  );
}

export function AlertDescription({ children, ...rest }: AlertPartProps) {
  return (
    <div {...rest} {...partAttrs("alert", "description")}>
      {children}
    </div>
  );
}

export function AlertAction({ children, ...rest }: AlertPartProps) {
  return (
    <div {...rest} {...partAttrs("alert", "action")}>
      {children}
    </div>
  );
}

/** The Alert anatomy, namespaced like every other Moderno primitive. */
export const Alert = {
  Root: AlertRoot,
  Icon: AlertIcon,
  Content: AlertContent,
  Title: AlertTitle,
  Description: AlertDescription,
  Action: AlertAction,
};

export type { AlertVariant, AlertSize } from "@moderno-ui/core";

// packages/solid/src/alert.tsx
import { splitProps, type JSX } from "solid-js";
import {
  alertRecipe,
  alertRole,
  partAttrs,
  type AlertSize,
  type AlertVariant,
} from "@moderno-ui/core";

export interface AlertRootProps extends JSX.HTMLAttributes<HTMLDivElement> {
  variant?: AlertVariant;
  size?: AlertSize;
}

/** Props of every non-root Alert part: a plain div, styled by its `data-part`. */
export type AlertPartProps = JSX.HTMLAttributes<HTMLDivElement>;

/**
 * Alert — an inline, page-level status message, ported to Solid.
 *
 * Identical contract to `@moderno-ui/react`: a CSS-only primitive whose parts
 * carry `data-scope`/`data-part` plus the shared `alertRecipe`'s
 * `data-variant`/`data-size`, painted entirely by `components.css`. `role`
 * defaults from the shared `alertRole` and is resolved (not spread over), so a
 * consumer's `role` wins while `undefined` keeps the default.
 */
export function AlertRoot(props: AlertRootProps) {
  const [local, rest] = splitProps(props, ["variant", "size", "role", "children"]);
  return (
    <div
      {...rest}
      role={local.role ?? alertRole(local.variant)}
      {...partAttrs("alert", "root")}
      {...alertRecipe({ variant: local.variant, size: local.size })}
    >
      {local.children}
    </div>
  );
}

export function AlertIcon(props: AlertPartProps) {
  const [local, rest] = splitProps(props, ["children", "aria-hidden"]);
  return (
    <div {...rest} aria-hidden={local["aria-hidden"] ?? true} {...partAttrs("alert", "icon")}>
      {local.children}
    </div>
  );
}

export function AlertContent(props: AlertPartProps) {
  const [local, rest] = splitProps(props, ["children"]);
  return (
    <div {...rest} {...partAttrs("alert", "content")}>
      {local.children}
    </div>
  );
}

export function AlertTitle(props: AlertPartProps) {
  const [local, rest] = splitProps(props, ["children"]);
  return (
    <div {...rest} {...partAttrs("alert", "title")}>
      {local.children}
    </div>
  );
}

export function AlertDescription(props: AlertPartProps) {
  const [local, rest] = splitProps(props, ["children"]);
  return (
    <div {...rest} {...partAttrs("alert", "description")}>
      {local.children}
    </div>
  );
}

export function AlertAction(props: AlertPartProps) {
  const [local, rest] = splitProps(props, ["children"]);
  return (
    <div {...rest} {...partAttrs("alert", "action")}>
      {local.children}
    </div>
  );
}

/** The Alert anatomy, namespaced like every other Moderno primitive. */
export const Alert = {
  Root: AlertRoot,
  Icon: AlertIcon,
  Content: AlertContent,
  Title: AlertTitle,
  Description: AlertDescription,
  Action: AlertAction,
};

export type { AlertVariant, AlertSize } from "@moderno-ui/core";
